apps:
- name: live
  lua-path: callback/
  rtmp:
    enble: true
    listen:
    - 0.0.0.0:1935
  http:
    flv:
      enble: true
    im:
      enble: true
    listen:
    - 0.0.0.0:9090
  http-demo:
    enble: true
